services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: 02230283_DSO101_A1/backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: your-render-db-host
      - key: DB_USER
        value: render_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: PORT
        value: 5000
      - key: DB_URI
        value: postgresql://render_db_user:your_db_password@your-render-db-host:5432/todo_db

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: 02230283_DSO101_A1/frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02230283.onrender.com/

databases:
  - name: todo-db
    databaseName: todo_db
    user: render_db_user