name: Build and Push Docker Images

on:
  push:
    branches: [ main ]  # Change this to your default branch if different
  pull_request:
    branches: [ main ]  # Change this to your default branch if different

jobs:
  build-and-push-image1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.kanishapradhan }}
          password: ${{ secrets.dckr_pat_CeG3IhJAZplm6iXBipsyus3-7uU }}
      
      - name: Build and push Image 1
        uses: docker/build-push-action@v6
        with:
          context: ./frontend  # Path to your first image directory
          file: ./frontend/Dockerfile  # Path to your first Dockerfile
          push: true
          tags: ${{ secrets.kanishapradhan }}/image1:latest
          
  build-and-push-image2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.kanishapradhan }}
          password: ${{ secrets.dckr_pat_CeG3IhJAZplm6iXBipsyus3-7uU }}
      
      - name: Build and push Image 2
        uses: docker/build-push-action@v6
        with:
          context: ./backend  # Path to your second image directory
          file: ./backend/Dockerfile  # Path to your second Dockerfile
          push: true
          tags: ${{ secrets.kanishapradhan }}/image2:latest